import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  // Schema already applied by Payload dev-mode auto-push; this is a no-op marker.
  await db.execute(sql`SELECT 1`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_rooms_category" AS ENUM('room', 'suite', 'villa', 'tent', 'cabin');
  ALTER TABLE "pages_blocks_content_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_content_section_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_card_grid_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_card_grid_cards_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_card_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_card_grid_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_content_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_content_section_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_card_grid_cards" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_card_grid_cards_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_card_grid" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_card_grid_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "room_groups" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "room_groups_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_rooms_v_version_inclusions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_rooms_v_version_inclusions_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_rooms_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_rooms_v_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_rooms_v_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "amenity_groups" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "amenity_groups_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "amenities_highlights" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "amenities_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "faq_categories_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "faq_categories_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "faq_categories" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "faq_categories_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_slides_benefits" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_slides_benefits_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_slides" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_slides_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_inclusions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_inclusions_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "auri_homepage_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_version_slides_benefits" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_version_slides_benefits_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_version_slides" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_version_slides_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_version_inclusions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_version_inclusions_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_auri_homepage_v_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_slides_benefits" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_slides_benefits_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_slides" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_slides_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_inclusions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_inclusions_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "orbis_homepage_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_version_slides_benefits" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_version_slides_benefits_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_version_slides" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_version_slides_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_version_inclusions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_version_inclusions_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_orbis_homepage_v_rels" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "pages_blocks_content_section" CASCADE;
  DROP TABLE "pages_blocks_content_section_locales" CASCADE;
  DROP TABLE "pages_blocks_card_grid_cards" CASCADE;
  DROP TABLE "pages_blocks_card_grid_cards_locales" CASCADE;
  DROP TABLE "pages_blocks_card_grid" CASCADE;
  DROP TABLE "pages_blocks_card_grid_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_content_section" CASCADE;
  DROP TABLE "_pages_v_blocks_content_section_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_card_grid_cards" CASCADE;
  DROP TABLE "_pages_v_blocks_card_grid_cards_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_card_grid" CASCADE;
  DROP TABLE "_pages_v_blocks_card_grid_locales" CASCADE;
  DROP TABLE "room_groups" CASCADE;
  DROP TABLE "room_groups_locales" CASCADE;
  DROP TABLE "_rooms_v_version_inclusions" CASCADE;
  DROP TABLE "_rooms_v_version_inclusions_locales" CASCADE;
  DROP TABLE "_rooms_v" CASCADE;
  DROP TABLE "_rooms_v_locales" CASCADE;
  DROP TABLE "_rooms_v_rels" CASCADE;
  DROP TABLE "amenity_groups" CASCADE;
  DROP TABLE "amenity_groups_locales" CASCADE;
  DROP TABLE "amenities_highlights" CASCADE;
  DROP TABLE "amenities_rels" CASCADE;
  DROP TABLE "faq_categories_items" CASCADE;
  DROP TABLE "faq_categories_items_locales" CASCADE;
  DROP TABLE "faq_categories" CASCADE;
  DROP TABLE "faq_categories_locales" CASCADE;
  DROP TABLE "auri_homepage_slides_benefits" CASCADE;
  DROP TABLE "auri_homepage_slides_benefits_locales" CASCADE;
  DROP TABLE "auri_homepage_slides" CASCADE;
  DROP TABLE "auri_homepage_slides_locales" CASCADE;
  DROP TABLE "auri_homepage_inclusions" CASCADE;
  DROP TABLE "auri_homepage_inclusions_locales" CASCADE;
  DROP TABLE "auri_homepage" CASCADE;
  DROP TABLE "auri_homepage_locales" CASCADE;
  DROP TABLE "auri_homepage_rels" CASCADE;
  DROP TABLE "_auri_homepage_v_version_slides_benefits" CASCADE;
  DROP TABLE "_auri_homepage_v_version_slides_benefits_locales" CASCADE;
  DROP TABLE "_auri_homepage_v_version_slides" CASCADE;
  DROP TABLE "_auri_homepage_v_version_slides_locales" CASCADE;
  DROP TABLE "_auri_homepage_v_version_inclusions" CASCADE;
  DROP TABLE "_auri_homepage_v_version_inclusions_locales" CASCADE;
  DROP TABLE "_auri_homepage_v" CASCADE;
  DROP TABLE "_auri_homepage_v_locales" CASCADE;
  DROP TABLE "_auri_homepage_v_rels" CASCADE;
  DROP TABLE "orbis_homepage_slides_benefits" CASCADE;
  DROP TABLE "orbis_homepage_slides_benefits_locales" CASCADE;
  DROP TABLE "orbis_homepage_slides" CASCADE;
  DROP TABLE "orbis_homepage_slides_locales" CASCADE;
  DROP TABLE "orbis_homepage_inclusions" CASCADE;
  DROP TABLE "orbis_homepage_inclusions_locales" CASCADE;
  DROP TABLE "orbis_homepage" CASCADE;
  DROP TABLE "orbis_homepage_locales" CASCADE;
  DROP TABLE "orbis_homepage_rels" CASCADE;
  DROP TABLE "_orbis_homepage_v_version_slides_benefits" CASCADE;
  DROP TABLE "_orbis_homepage_v_version_slides_benefits_locales" CASCADE;
  DROP TABLE "_orbis_homepage_v_version_slides" CASCADE;
  DROP TABLE "_orbis_homepage_v_version_slides_locales" CASCADE;
  DROP TABLE "_orbis_homepage_v_version_inclusions" CASCADE;
  DROP TABLE "_orbis_homepage_v_version_inclusions_locales" CASCADE;
  DROP TABLE "_orbis_homepage_v" CASCADE;
  DROP TABLE "_orbis_homepage_v_locales" CASCADE;
  DROP TABLE "_orbis_homepage_v_rels" CASCADE;
  ALTER TABLE "rooms" DROP CONSTRAINT "rooms_group_id_room_groups_id_fk";
  
  ALTER TABLE "amenities" DROP CONSTRAINT "amenities_group_id_amenity_groups_id_fk";
  
  ALTER TABLE "amenities" DROP CONSTRAINT "amenities_hero_image_id_media_id_fk";
  
  ALTER TABLE "redirects_rels" DROP CONSTRAINT "redirects_rels_properties_fk";
  
  ALTER TABLE "redirects_rels" DROP CONSTRAINT "redirects_rels_offers_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_room_groups_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_amenity_groups_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_faq_categories_fk";
  
  ALTER TABLE "site_settings" DROP CONSTRAINT "site_settings_favicon_id_media_id_fk";
  
  DROP INDEX "pages_path_idx";
  DROP INDEX "_pages_v_version_version_path_idx";
  DROP INDEX "rooms_group_idx";
  DROP INDEX "rooms__status_idx";
  DROP INDEX "amenities_slug_idx";
  DROP INDEX "amenities_group_idx";
  DROP INDEX "amenities_hero_image_idx";
  DROP INDEX "redirects_rels_properties_id_idx";
  DROP INDEX "redirects_rels_offers_id_idx";
  DROP INDEX "payload_locked_documents_rels_room_groups_id_idx";
  DROP INDEX "payload_locked_documents_rels_amenity_groups_id_idx";
  DROP INDEX "payload_locked_documents_rels_faq_categories_id_idx";
  DROP INDEX "site_settings_favicon_idx";
  ALTER TABLE "rooms_inclusions_locales" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "rooms" ALTER COLUMN "slug" SET NOT NULL;
  ALTER TABLE "rooms" ALTER COLUMN "property_id" SET NOT NULL;
  ALTER TABLE "rooms_locales" ALTER COLUMN "name" SET NOT NULL;
  ALTER TABLE "pages_locales" ADD COLUMN "meta_image_id" integer;
  ALTER TABLE "_pages_v_locales" ADD COLUMN "version_meta_image_id" integer;
  ALTER TABLE "properties_rels" ADD COLUMN "amenities_id" integer;
  ALTER TABLE "rooms" ADD COLUMN "category" "enum_rooms_category" NOT NULL;
  ALTER TABLE "amenities" ADD COLUMN "icon" varchar NOT NULL;
  ALTER TABLE "amenities_locales" ADD COLUMN "category" varchar;
  ALTER TABLE "pages_locales" ADD CONSTRAINT "pages_locales_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_locales" ADD CONSTRAINT "_pages_v_locales_version_meta_image_id_media_id_fk" FOREIGN KEY ("version_meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "properties_rels" ADD CONSTRAINT "properties_rels_amenities_fk" FOREIGN KEY ("amenities_id") REFERENCES "public"."amenities"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_meta_meta_image_idx" ON "pages_locales" USING btree ("meta_image_id","_locale");
  CREATE INDEX "_pages_v_version_meta_version_meta_image_idx" ON "_pages_v_locales" USING btree ("version_meta_image_id","_locale");
  CREATE INDEX "properties_rels_amenities_id_idx" ON "properties_rels" USING btree ("amenities_id");
  ALTER TABLE "pages" DROP COLUMN "path";
  ALTER TABLE "_pages_v" DROP COLUMN "version_path";
  ALTER TABLE "properties_locales" DROP COLUMN "meta_title";
  ALTER TABLE "properties_locales" DROP COLUMN "meta_description";
  ALTER TABLE "rooms" DROP COLUMN "group_id";
  ALTER TABLE "rooms" DROP COLUMN "_status";
  ALTER TABLE "rooms_locales" DROP COLUMN "meta_title";
  ALTER TABLE "rooms_locales" DROP COLUMN "meta_description";
  ALTER TABLE "offers_locales" DROP COLUMN "meta_title";
  ALTER TABLE "offers_locales" DROP COLUMN "meta_description";
  ALTER TABLE "_offers_v_locales" DROP COLUMN "version_meta_title";
  ALTER TABLE "_offers_v_locales" DROP COLUMN "version_meta_description";
  ALTER TABLE "amenities" DROP COLUMN "slug";
  ALTER TABLE "amenities" DROP COLUMN "group_id";
  ALTER TABLE "amenities" DROP COLUMN "hero_image_id";
  ALTER TABLE "amenities" DROP COLUMN "order";
  ALTER TABLE "amenities_locales" DROP COLUMN "tagline";
  ALTER TABLE "amenities_locales" DROP COLUMN "description";
  ALTER TABLE "amenities_locales" DROP COLUMN "opening_hours";
  ALTER TABLE "amenities_locales" DROP COLUMN "location";
  ALTER TABLE "redirects_rels" DROP COLUMN "properties_id";
  ALTER TABLE "redirects_rels" DROP COLUMN "offers_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "room_groups_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "amenity_groups_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "faq_categories_id";
  ALTER TABLE "site_settings" DROP COLUMN "favicon_id";
  ALTER TABLE "site_settings" DROP COLUMN "google_analytics_id";
  DROP TYPE "public"."enum_pages_blocks_content_section_image_position";
  DROP TYPE "public"."enum__pages_v_blocks_content_section_image_position";
  DROP TYPE "public"."enum_rooms_status";
  DROP TYPE "public"."enum__rooms_v_version_status";
  DROP TYPE "public"."enum__rooms_v_published_locale";
  DROP TYPE "public"."enum_auri_homepage_status";
  DROP TYPE "public"."enum__auri_homepage_v_version_status";
  DROP TYPE "public"."enum__auri_homepage_v_published_locale";
  DROP TYPE "public"."enum_orbis_homepage_status";
  DROP TYPE "public"."enum__orbis_homepage_v_version_status";
  DROP TYPE "public"."enum__orbis_homepage_v_published_locale";`)
}
